classes: {
  app: {
    style: {
      fill: darkorange
    }
  }
  web: {
    style: {
      fill: darkturquoise
    }
  }
  player1: {
    shape: circle
    style: {
      fill: crimson
    }
  }
  player2: {
    shape: circle
    style: {
      fill: springgreen
    }
  }
  bdd: {
    shape: cylinder
    style: {
      fill: deepskyblue
    }
  }
  pkg: {
    shape: package
    style: {
      fill: silver
    }
  }
}
